/**
 * Greeting
 *
 * The Greeting program implements an application that displays the traditional first-world message to the standard
 * output, however it does so in another language
 *
 * @author Michael Sammels
 * @version 10.09.2018
 */

public class Greeting {
    /**
     * The main launcher method
     * @param args Command line arguments (unused)
     */
    public static void main(String[] args) {
        System.out.println("Konnichiwa, Sekai!");
    }
}
